"""
DRF ViewSets for jobs and executions.

Endpoints (auto-generated by DefaultRouter):
- GET    /api/jobs/                    list current user's jobs
- POST   /api/jobs/                    create a job
- GET    /api/jobs/{public_id}/        retrieve one
- PUT    /api/jobs/{public_id}/        replace
- PATCH  /api/jobs/{public_id}/        partial update
- DELETE /api/jobs/{public_id}/        delete
- POST   /api/jobs/{public_id}/trigger/  manual fire (custom action)
- GET    /api/jobs/{public_id}/executions/  scoped execution list

- GET    /api/executions/              flat list of user's executions
- GET    /api/executions/{public_id}/  retrieve one
"""

from django.db import transaction
from django.utils import timezone
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import mixins, status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from .models import Job, JobExecution
from .serializers import JobExecutionSerializer, JobSerializer
from .tasks import execute_job_execution


class JobViewSet(viewsets.ModelViewSet):
    """Full CRUD on jobs, scoped to the requesting user."""

    serializer_class = JobSerializer
    lookup_field = "public_id"
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["is_active", "http_method"]
    ordering_fields = ["created_at", "next_fire_at", "name"]
    ordering = ["-created_at"]

    def get_queryset(self):
        # Users only see their own jobs. Ever.
        return Job.objects.filter(owner=self.request.user)

    def perform_create(self, serializer):
        # Set owner from the authenticated request, not from client input.
        serializer.save(owner=self.request.user)

    @action(detail=True, methods=["post"])
    def trigger(self, request, public_id=None):
        """
        Manually fire a job right now, bypassing the schedule.

        Creates a JobExecution with scheduled_for=now, then dispatches
        the executor task. Returns the created execution.
        """
        job = self.get_object()

        with transaction.atomic():
            execution = JobExecution.objects.create(
                job=job,
                scheduled_for=timezone.now(),
                status=JobExecution.Status.PENDING,
            )
        transaction.on_commit(lambda: execute_job_execution.delay(execution.id))

        serializer = JobExecutionSerializer(execution)
        return Response(serializer.data, status=status.HTTP_202_ACCEPTED)

    @action(detail=True, methods=["get"])
    def executions(self, request, public_id=None):
        """List execution history for one job (paginated)."""
        job = self.get_object()
        qs = job.executions.all()
        page = self.paginate_queryset(qs)
        if page is not None:
            serializer = JobExecutionSerializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        serializer = JobExecutionSerializer(qs, many=True)
        return Response(serializer.data)


class JobExecutionViewSet(
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin,
    viewsets.GenericViewSet,
):
    """Read-only view of ALL executions belonging to the user's jobs."""

    serializer_class = JobExecutionSerializer
    lookup_field = "public_id"
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["status", "job__public_id"]
    ordering_fields = ["scheduled_for", "started_at", "finished_at"]
    ordering = ["-scheduled_for"]

    def get_queryset(self):
        return JobExecution.objects.filter(job__owner=self.request.user).select_related("job")
