# Generated by Django 5.1.4 on 2026-07-02 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("target_url", models.URLField(max_length=2000)),
                (
                    "http_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="POST",
                        max_length=10,
                    ),
                ),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("body", models.TextField(blank=True, default="")),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("schedule_cron", models.CharField(max_length=100)),
                ("next_fire_at", models.DateTimeField(blank=True, null=True)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("retry_backoff_seconds", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobExecution",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("http_status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("response_body_snippet", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="jobs.job",
                    ),
                ),
                (
                    "parent_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="jobs.jobexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active", "next_fire_at"], name="job_active_next_fire_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["owner", "-created_at"], name="job_owner_created_idx"),
        ),
        migrations.AddIndex(
            model_name="jobexecution",
            index=models.Index(fields=["job", "-started_at"], name="exec_job_started_idx"),
        ),
        migrations.AddIndex(
            model_name="jobexecution",
            index=models.Index(fields=["status", "scheduled_for"], name="exec_status_sched_idx"),
        ),
    ]
