# Generated by Django 5.1.4 on 2026-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="alert_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="job",
            name="alert_webhook_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
    ]
